/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: definitions/foo/user.proto */

#ifndef PROTOBUF_C_definitions_2ffoo_2fuser_2eproto__INCLUDED
#define PROTOBUF_C_definitions_2ffoo_2fuser_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Foo__User Foo__User;


/* --- enums --- */


/* --- messages --- */

struct  _Foo__User
{
  ProtobufCMessage base;
  char *first_name;
  char *last_name;
};
#define FOO__USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foo__user__descriptor) \
    , NULL, NULL }


/* Foo__User methods */
void   foo__user__init
                     (Foo__User         *message);
size_t foo__user__get_packed_size
                     (const Foo__User   *message);
size_t foo__user__pack
                     (const Foo__User   *message,
                      uint8_t             *out);
size_t foo__user__pack_to_buffer
                     (const Foo__User   *message,
                      ProtobufCBuffer     *buffer);
Foo__User *
       foo__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foo__user__free_unpacked
                     (Foo__User *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foo__User_Closure)
                 (const Foo__User *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foo__user__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_definitions_2ffoo_2fuser_2eproto__INCLUDED */
