/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: definitions/foo/user.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "definitions/foo/user.pb-c.h"
void   foo__user__init
                     (Foo__User         *message)
{
  static Foo__User init_value = FOO__USER__INIT;
  *message = init_value;
}
size_t foo__user__get_packed_size
                     (const Foo__User *message)
{
  assert(message->base.descriptor == &foo__user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__user__pack
                     (const Foo__User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__user__pack_to_buffer
                     (const Foo__User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__User *
       foo__user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__User *)
     protobuf_c_message_unpack (&foo__user__descriptor,
                                allocator, len, data);
}
void   foo__user__free_unpacked
                     (Foo__User *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &foo__user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foo__user__field_descriptors[2] =
{
  {
    "first_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__User, first_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__User, last_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__user__field_indices_by_name[] = {
  0,   /* field[0] = first_name */
  1,   /* field[1] = last_name */
};
static const ProtobufCIntRange foo__user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor foo__user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.User",
  "User",
  "Foo__User",
  "foo",
  sizeof(Foo__User),
  2,
  foo__user__field_descriptors,
  foo__user__field_indices_by_name,
  1,  foo__user__number_ranges,
  (ProtobufCMessageInit) foo__user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
