// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

#ifndef PROTOBUF_user_2eproto__INCLUDED
#define PROTOBUF_user_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace foo {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_user_2eproto();
void protobuf_AssignDesc_user_2eproto();
void protobuf_ShutdownFile_user_2eproto();

class User;

// ===================================================================

class User : public ::google::protobuf::Message {
 public:
  User();
  virtual ~User();

  User(const User& from);

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const User& default_instance();

  void Swap(User* other);

  // implements Message ----------------------------------------------

  User* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const User& from);
  void MergeFrom(const User& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string first_name = 1;
  inline bool has_first_name() const;
  inline void clear_first_name();
  static const int kFirstNameFieldNumber = 1;
  inline const ::std::string& first_name() const;
  inline void set_first_name(const ::std::string& value);
  inline void set_first_name(const char* value);
  inline void set_first_name(const char* value, size_t size);
  inline ::std::string* mutable_first_name();
  inline ::std::string* release_first_name();
  inline void set_allocated_first_name(::std::string* first_name);

  // optional string last_name = 2;
  inline bool has_last_name() const;
  inline void clear_last_name();
  static const int kLastNameFieldNumber = 2;
  inline const ::std::string& last_name() const;
  inline void set_last_name(const ::std::string& value);
  inline void set_last_name(const char* value);
  inline void set_last_name(const char* value, size_t size);
  inline ::std::string* mutable_last_name();
  inline ::std::string* release_last_name();
  inline void set_allocated_last_name(::std::string* last_name);

  // @@protoc_insertion_point(class_scope:foo.User)
 private:
  inline void set_has_first_name();
  inline void clear_has_first_name();
  inline void set_has_last_name();
  inline void clear_has_last_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* first_name_;
  ::std::string* last_name_;
  friend void  protobuf_AddDesc_user_2eproto();
  friend void protobuf_AssignDesc_user_2eproto();
  friend void protobuf_ShutdownFile_user_2eproto();

  void InitAsDefaultInstance();
  static User* default_instance_;
};
// ===================================================================


// ===================================================================

// User

// optional string first_name = 1;
inline bool User::has_first_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void User::set_has_first_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void User::clear_has_first_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void User::clear_first_name() {
  if (first_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    first_name_->clear();
  }
  clear_has_first_name();
}
inline const ::std::string& User::first_name() const {
  // @@protoc_insertion_point(field_get:foo.User.first_name)
  return *first_name_;
}
inline void User::set_first_name(const ::std::string& value) {
  set_has_first_name();
  if (first_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    first_name_ = new ::std::string;
  }
  first_name_->assign(value);
  // @@protoc_insertion_point(field_set:foo.User.first_name)
}
inline void User::set_first_name(const char* value) {
  set_has_first_name();
  if (first_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    first_name_ = new ::std::string;
  }
  first_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:foo.User.first_name)
}
inline void User::set_first_name(const char* value, size_t size) {
  set_has_first_name();
  if (first_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    first_name_ = new ::std::string;
  }
  first_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:foo.User.first_name)
}
inline ::std::string* User::mutable_first_name() {
  set_has_first_name();
  if (first_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    first_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:foo.User.first_name)
  return first_name_;
}
inline ::std::string* User::release_first_name() {
  clear_has_first_name();
  if (first_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = first_name_;
    first_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void User::set_allocated_first_name(::std::string* first_name) {
  if (first_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete first_name_;
  }
  if (first_name) {
    set_has_first_name();
    first_name_ = first_name;
  } else {
    clear_has_first_name();
    first_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:foo.User.first_name)
}

// optional string last_name = 2;
inline bool User::has_last_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void User::set_has_last_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void User::clear_has_last_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void User::clear_last_name() {
  if (last_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    last_name_->clear();
  }
  clear_has_last_name();
}
inline const ::std::string& User::last_name() const {
  // @@protoc_insertion_point(field_get:foo.User.last_name)
  return *last_name_;
}
inline void User::set_last_name(const ::std::string& value) {
  set_has_last_name();
  if (last_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    last_name_ = new ::std::string;
  }
  last_name_->assign(value);
  // @@protoc_insertion_point(field_set:foo.User.last_name)
}
inline void User::set_last_name(const char* value) {
  set_has_last_name();
  if (last_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    last_name_ = new ::std::string;
  }
  last_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:foo.User.last_name)
}
inline void User::set_last_name(const char* value, size_t size) {
  set_has_last_name();
  if (last_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    last_name_ = new ::std::string;
  }
  last_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:foo.User.last_name)
}
inline ::std::string* User::mutable_last_name() {
  set_has_last_name();
  if (last_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    last_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:foo.User.last_name)
  return last_name_;
}
inline ::std::string* User::release_last_name() {
  clear_has_last_name();
  if (last_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = last_name_;
    last_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void User::set_allocated_last_name(::std::string* last_name) {
  if (last_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete last_name_;
  }
  if (last_name) {
    set_has_last_name();
    last_name_ = last_name;
  } else {
    clear_has_last_name();
    last_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:foo.User.last_name)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace foo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_user_2eproto__INCLUDED
